# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-API

  target 'Test-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-APIUITests' do
    # Pods for testing
  end
	pod 'Alamofire', '~> 5.2'

end
